### ISSUE TITLE
Data structure for npy files

### ISSUE THREAD

**Issue by albertchristian92** [olly-styles/Multiple-Object-Forecasting#13]
Hi olly, actually I already successfully implemented your DTP paper using different dataset:

https://arxiv.org/pdf/1905.03681.pdf

and when I want to implement MOF, I realize the data structure for .npy files is not same with the output from DTP.  The DTP code resulting as shown:
![result](https://user-images.githubusercontent.com/12479762/89780713-8f7fd500-db44-11ea-97e0-e7c9498f425a.png)

But in MOF, as I see in your pre-trained data:
![pretrain](https://user-images.githubusercontent.com/12479762/89780797-b2aa8480-db44-11ea-826f-1a6f9d6414e1.png)
There are three kinds of .npy files:
- dtp_box_statistics 
- dtp_features
- dtp_targets

would you mind explain to me what is the data structure for these .npy files?Because I cannot find these information in your paper. Thank you very much

**Comment by olly-styles** [comment]
Thanks for your interest in our work. Happy to help out.

dtp_box_statistics: These are the inputs to the bounding box encoder, as described in Section 5.1 of the paper.
dtp_features: These are the pre-computed outputs from the optical flow encoder, i.e. φf. We pre-computed and saved these rather than computing them on-the-fly to reduce the computation time. 
dtp_targets: These are the target future bounding boxes, i.e. b_{t+1} ... b_{t+60}

I hope that clears things up. Please let me know if you have any more questions.
