### ISSUE TITLE
Questions about train_box.npy?

### ISSUE THREAD

**Issue by Senwang98** [olly-styles/Multiple-Object-Forecasting#9]
Hi, olly
train_box.npy size=(169341,8,25), what's the meaning of '25'?

**Comment by alexivaner** [comment]
Yes, I still not yet figured how is the structure of this NPY file, if @olly-styles could help to explain, it will help us a lot. Thank you.

**Comment by Senwang98** [comment]
Because DTP's para setting is different from MOF's, so i am not sure '25' means 10 previous frames and 15 future frames.
DTP's FPS is 15 and use previous 10 frames to predict next 15 frames.
MOF's FPS is 30 and use previous 30 frames to predict next 60 frames.

**Comment by olly-styles** [comment]
Hi both,

Sorry for the confusing representation. The numpy file is structured as (sample, bounding box with statistics, timestep), In the paper, we state:

"In addition, we compute the velocity in the x and y directions, change in width, ∆w, and change
in height, ∆h. This results in an 8-dimensional vector associated with each object bounding box"

These velocity and change in width/height features are computed using 5 frames, i.e., x velocity at t = x_{t-5} - x_{t}. To compute these we must have at least 5 timesteps, so the features represent timesteps t-25 to t. This is the reason the file looks like (169341,8,25) rather than (169341,8,30).

Hope that helps,
Olly

**Comment by Senwang98** [comment]
Okay, so the 30 optical flow frames are splited into two parts, the previous 25 frames are changeless and left 5 frames are used to get avrage velc?
Thank olly, this makes me understand your paper better!

**Comment by 1187697147** [comment]
Now I have used deepsort to get a file in the same format as your tracking result. In the process of converting it into an npy file, I want to know if the 25 frames from _t-_25 to _t_ in the past 30 frames are used as features, and then _t-_29~_t_-25 as the frame for speed calculation

**Comment by 1187697147** [comment]
Hi, olly
By the way, i still have a question about save order.
Assuming that the current frame is t, what is the order in which you save frames t-24~t? My approach is to find a frame (labeled = 1), read a total of 30 frames from t-29 to t, t-24 is the first frame that needs to be saved, and save it until t in chronological order. I wonder if there is a problem with my approach?
I think the calculated speed from t-29~t-25 is vx, vy, delta_w, delta_h required by t-24.

**Comment by 1187697147** [comment]
Hi, olly
By the way, i still have a question about save order.
Assuming that the current frame is t, what is the order in which you save frames t-24~t? My approach is to find a frame (labeled = 1), read a total of 30 frames from t-29 to t, t-24 is the first frame that needs to be saved, and save it until t in chronological order. I wonder if there is a problem with my approach?
I think the calculated speed from t-29~t-25 is vx, vy, delta_w, delta_h required by t-24.
